import { Circle, Mars, Transgender, User, UserCog, Users, Venus } from 'lucide-react';

export interface GenderOption {
  value: string;
  label: string;
  icon: any;
}

export interface RoleOption {
  value: string;
  label: string;
  icon: any;
}

export const genderOptions: GenderOption[] = [
  { value: 'male', label: 'Male', icon: Mars },
  { value: 'female', label: 'Female', icon: Venus },
  { value: 'other', label: 'Other', icon: Transgender },
  { value: 'not specify', label: 'Not Specify', icon: Circle },
];

export const roleOptions: RoleOption[] = [
  { value: 'patient', label: 'Patient', icon: User },
  { value: 'team', label: 'Team', icon: Users },
  { value: 'freelancer', label: 'Freelancer', icon: UserCog },
];

// Irish cities, towns, and villages (deduplicated)
export const irishLocations: string[] = [
  'Dublin',
  'Cork',
  'Galway',
  'Limerick',
  'Waterford',
  'Kilkenny',
  'Wexford',
  'Sligo',
  'Dundalk',
  'Bray',
  'Navan',
  'Ennis',
  'Tralee',
  'Carlow',
  'Newbridge',
  'Portlaoise',
  'Mullingar',
  'Wicklow',
  'Tullamore',
  'Longford',
  'Roscommon',
  'Castlebar',
  'Ballina',
  'Letterkenny',
  'Monaghan',
  'Cavan',
  'Athlone',
  'Clonmel',
  'Tipperary',
  'Thurles',
  'Nenagh',
  'Killarney',
  'Listowel',
  'Bandon',
  'Clonakilty',
  'Skibbereen',
  'Bantry',
  'Kinsale',
  'Youghal',
  'Dungarvan',
  'Tramore',
  'Arklow',
  'Gorey',
  'Enniscorthy',
  'New Ross',
  'Greystones',
  'Dun Laoghaire',
  'Blackrock',
  'Dalkey',
  'Killiney',
  'Booterstown',
  'Malahide',
  'Swords',
  'Balbriggan',
  'Rush',
  'Lusk',
  'Donabate',
  'Portmarnock',
  'Howth',
  'Sutton',
  'Baldoyle',
  'Raheny',
  'Clontarf',
  'Killester',
  'Artane',
  'Coolock',
  'Ballymun',
  'Finglas',
  'Blanchardstown',
  'Castleknock',
  'Lucan',
  'Leixlip',
  'Maynooth',
  'Celbridge',
  'Naas',
  'Kildare',
  'Athy',
  'Portarlington',
  'Mountmellick',
  'Birr',
  'Banagher',
  'Ballinasloe',
  'Loughrea',
  'Athenry',
  'Tuam',
  'Westport',
  'Claremorris',
  'Ballyhaunis',
  'Castlerea',
  'Boyle',
  'Carrick-on-Shannon',
  'Granard',
  'Moate',
  'Kilbeggan',
  'Edenderry',
  'Mountrath',
  'Abbeyleix',
  'Durrow',
  'Callan',
  'Thomastown',
  'Gowran',
  'Castlecomer',
  'Freshford',
  'Urlingford',
  'Johnstown',
  'Tullow',
  'Muine Bheag',
  'Leighlinbridge',
  'Rathvilly',
  'Hacketstown',
  'Newtownmountkennedy',
  'Kilcoole',
  'Blessington',
  'Baltinglass',
  'Tinahely',
  'Shillelagh',
  'Carnew',
  'Bunclody',
  'Ferns',
  'Monageer',
  'Rosslare',
  'Kilmore Quay',
  'Courtown',
  'Blackwater',
  'Oulart',
  'Castlebridge',
  'Curracloe',
  'Fethard',
  'Lismore',
  'Tallow',
  'Cappoquin',
  'Kill',
  'Portlaw',
  'Carrick-on-Suir',
  'Cahir',
  'Cashel',
  'Roscrea',
  'Templemore',
  'Borrisokane',
  'Newport',
  'Killaloe',
  'Scariff',
  'Newcastle West',
  'Rathkeale',
  'Adare',
  'Askeaton',
  'Abbeyfeale',
  'Kilmallock',
  'Bruff',
  'Croom',
  'Patrickswell',
  'Cobh',
  'Midleton',
  'Castletownbere',
  'Killorglin',
  'Cahersiveen',
  'Kenmare',
  'Dingle',
  'Castlegregory',
  'Ballybunion',
  'Ballyheigue',
  'Gort',
  'Oranmore',
  'Clarinbridge',
  'Kilcolgan',
  'Craughwell',
  'Ballymote',
  'Tubbercurry',
  'Gurteen',
  'Collooney',
  'Ballygawley',
  'Strandhill',
  'Rosses Point',
  'Enniscrone',
  'Easkey',
  'Mayo',
  'Swinford',
  'Foxford',
  'Killala',
  'Ballinrobe',
  'Donegal',
  'Buncrana',
  'Bundoran',
  'Donegal Town',
  'Ballyshannon',
  'Carndonagh',
  'Moville',
  'Dunfanaghy',
  'Ardara',
  'Carrickmacross',
  'Castleblayney',
  'Clones',
  'Ballybay',
  'Emyvale',
  'Scotstown',
  'Newbliss',
  'Rockcorry',
  'Belturbet',
  'Cootehill',
  'Virginia',
  'Bailieborough',
  'Kingscourt',
  'Mullagh',
  'Shercock',
  'Arvagh',
  'Killeshandra',
  'Louth',
  'Drogheda',
  'Ardee',
  'Dunleer',
  'Carlingford',
  'Omeath',
  'Termonfeckin',
  'Clogherhead',
  'Meath',
  'Trim',
  'Kells',
  'Dunshaughlin',
  'Ashbourne',
  'Ratoath',
  'Dunboyne',
  'Slane',
  'Laytown',
  'Bettystown',
];
